// ===== LANGUAGE STATE =====
function getLanguage() {
  return localStorage.getItem("selectedLanguage") === "tl" ? "tl" : "en";
}

function setLanguage(lang) {
  localStorage.setItem("selectedLanguage", lang === "tl" ? "tl" : "en");
}

// ===== UI STRINGS =====
const UI_STRINGS = {
  en: {
    login_tab_login: "Log In",
    login_tab_register: "Register",
    login_placeholder_username: "Username",
    login_placeholder_password: "Password",
    login_btn_submit_login: "Log In",
    login_btn_submit_register: "Register",
    login_or_divider: "— or —",
    login_btn_guest: "Play as Guest",
    login_err_missing_fields: "Enter a username and password.",
    login_err_username_taken: "That username is already taken.",
    login_err_wrong_credentials: "Incorrect username or password.",
    login_err_generic: "Something went wrong. Try again.",
    login_success_registered: "Account created! Log in below.",
    login_err_network: "Couldn't reach the server. Check your connection.",
    login_err_guest_missing: "Enter a username to play as guest.",

    menu_start: "Start Game",
    menu_characters: "Characters",
    menu_levels: "Levels",
    menu_ranks: "Ranks",
    menu_howtoplay: "How to Play",
    menu_logout: "Log Out",
    howtoplay_title: "📘 How to Play",
    howtoplay_body: "➤ Use arrow keys or on-screen buttons to move and jump.\n➤ Answer quiz questions correctly to progress through each level.\n➤ Finish all 3 levels of a topic to complete it.\n➤ More points makes you climb the ranks!",
    howtoplay_back: "Back to Menu",
    endscreen_title: "🏁 LEVEL COMPLETE!",
    endscreen_points_label: "Points:",
    endscreen_time_label: "Time:",
    endscreen_score_label: "Score:",
    endscreen_continue: "Continue",
    alert_choose_character: "Please choose a character first!",

    char_title: "Choose Your Character",
    char_confirm: "Confirm Character",
    char_back: "Back to Menu",
    char_msg_selected: "Character Selected!",
    char_msg_none: "Please select a character!",

    grade_title: "📚 Select Your Grade",
    grade_back: "⬅ Back",
    grade_7: "Grade 7",
    grade_8: "Grade 8",
    grade_9: "Grade 9",
    grade_10: "Grade 10",

    levelmap_back_main: "⬅ Main Menu",
    levelmap_back_subjects: "⬅ Subjects",
    levelmap_change_grade: "🎓 Change Grade",
    levelmap_select_subject: "Select Subject",

    levelselect_title: "🎮 Select Game Mode",
    levelselect_level1: "Level 1 — Platformer",
    levelselect_level2: "Level 2 — The Maze",
    levelselect_level3: "Level 3 — Flappy Flight",
    levelselect_back: "⬅ Back to Topics",

    hud_score_label: "Score:",
    hud_topic_label: "Topic:",
    summary_title: "Topic Complete!",
    summary_btn_mainmenu: "Main Menu",
    summary_btn_levelmap: "Level Map",
    summary_btn_ranks: "View Ranks",
    summary_btn_another: "Choose Another Topic",
    loading_text: "Loading questions...",
    error_title: "Couldn't load questions",
    error_body: "No offline questions exist for this topic yet. Check the Gemini API key/network and try again.",
    error_retry: "Retry",
    error_back: "Back to Topic Select",
    levelintro_go: "Go!",
    quiz_badge: "✨ Generated by Gemini",
    quiz_correct_feedback: "Correct! +{n} point(s)",
    quiz_wrong_feedback: "Wrong — correct answer highlighted.",
    levelintro_maze_text: "Answer questions to open the gates and find the exit! Correct answers are now worth {n} points each.",
    levelintro_flappy_text: "Tap or press Space to flap through the pipes! Correct answers are now worth {n} points each.",

    rank_title: "🏆 Leaderboard",
    rank_subtitle: "Top Players",
    rank_back: "⬅ Back"
  },
  tl: {
    login_tab_login: "Mag-log In",
    login_tab_register: "Magrehistro",
    login_placeholder_username: "Username",
    login_placeholder_password: "Password",
    login_btn_submit_login: "Mag-log In",
    login_btn_submit_register: "Magrehistro",
    login_or_divider: "— o —",
    login_btn_guest: "Maglaro bilang Bisita",
    login_err_missing_fields: "Maglagay ng username at password.",
    login_err_username_taken: "Nagamit na ang username na iyan.",
    login_err_wrong_credentials: "Maling username o password.",
    login_err_generic: "May nangyaring mali. Subukan muli.",
    login_success_registered: "Nagawa na ang account! Mag-log in sa ibaba.",
    login_err_network: "Hindi ma-reach ang server. Suriin ang iyong koneksyon.",
    login_err_guest_missing: "Maglagay ng username para maglaro bilang bisita.",

    menu_start: "Simulan ang Laro",
    menu_characters: "Mga Karakter",
    menu_levels: "Mga Level",
    menu_ranks: "Ranggo",
    menu_howtoplay: "Paano Maglaro",
    menu_logout: "Mag-log Out",
    howtoplay_title: "📘 Paano Maglaro",
    howtoplay_body: "➤ Gamitin ang arrow keys o mga on-screen button para gumalaw at tumalon.\n➤ Sagutin nang tama ang mga tanong para makasulong sa bawat level.\n➤ Tapusin ang lahat ng 3 level ng isang paksa para makumpleto ito.\n➤ Mas maraming puntos, mas mataas sa ranggo!",
    howtoplay_back: "Bumalik sa Menu",
    endscreen_title: "🏁 TAPOS NA ANG LEVEL!",
    endscreen_points_label: "Puntos:",
    endscreen_time_label: "Oras:",
    endscreen_score_label: "Iskor:",
    endscreen_continue: "Magpatuloy",
    alert_choose_character: "Pumili muna ng karakter!",

    char_title: "Piliin ang Iyong Karakter",
    char_confirm: "Kumpirmahin ang Karakter",
    char_back: "Bumalik sa Menu",
    char_msg_selected: "Napili ang Karakter!",
    char_msg_none: "Pumili ng karakter!",

    grade_title: "📚 Piliin ang Iyong Baitang",
    grade_back: "⬅ Bumalik",
    grade_7: "Baitang 7",
    grade_8: "Baitang 8",
    grade_9: "Baitang 9",
    grade_10: "Baitang 10",

    levelmap_back_main: "⬅ Pangunahing Menu",
    levelmap_back_subjects: "⬅ Mga Asignatura",
    levelmap_change_grade: "🎓 Baguhin ang Baitang",
    levelmap_select_subject: "Piliin ang Asignatura",

    levelselect_title: "🎮 Piliin ang Uri ng Laro",
    levelselect_level1: "Level 1 — Platformer",
    levelselect_level2: "Level 2 — Ang Labirinto",
    levelselect_level3: "Level 3 — Paglipad",
    levelselect_back: "⬅ Bumalik sa mga Paksa",

    hud_score_label: "Iskor:",
    hud_topic_label: "Paksa:",
    summary_title: "Tapos na ang Paksa!",
    summary_btn_mainmenu: "Pangunahing Menu",
    summary_btn_levelmap: "Mapa ng Level",
    summary_btn_ranks: "Tingnan ang Ranggo",
    summary_btn_another: "Pumili ng Ibang Paksa",
    loading_text: "Naglo-load ng mga tanong...",
    error_title: "Hindi ma-load ang mga tanong",
    error_body: "Wala pang offline na tanong para sa paksang ito. Suriin ang Gemini API key/koneksyon at subukan muli.",
    error_retry: "Subukan Muli",
    error_back: "Bumalik sa Pagpili ng Paksa",
    levelintro_go: "Sige!",
    quiz_badge: "✨ Ginawa ng Gemini",
    quiz_correct_feedback: "Tama! +{n} puntos",
    quiz_wrong_feedback: "Mali — naka-highlight ang tamang sagot.",
    levelintro_maze_text: "Sagutin ang mga tanong para mabuksan ang mga gate at mahanap ang labasan! Ang tamang sagot ay nagkakahalaga na ngayon ng {n} puntos bawat isa.",
    levelintro_flappy_text: "Pindutin o i-press ang Space para lumipad sa pagitan ng mga tubo! Ang tamang sagot ay nagkakahalaga na ngayon ng {n} puntos bawat isa.",

    rank_title: "🏆 Listahan ng mga Nangunguna",
    rank_subtitle: "Nangungunang mga Manlalaro",
    rank_back: "⬅ Bumalik"
  }
};

function t(key, vars) {
  const lang = getLanguage();
  let str = (UI_STRINGS[lang] && UI_STRINGS[lang][key]) || UI_STRINGS.en[key] || key;
  if (vars) {
    Object.keys(vars).forEach(k => { str = str.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]); });
  }
  return str;
}

// ===== SUBJECT / TOPIC DISPLAY LABELS (display only — never used as storage/lookup keys) =====
const SUBJECT_LABELS = {
  en: { "Science": "Science", "Math": "Math", "English/Reading": "English/Reading" },
  tl: { "Science": "Agham", "Math": "Matematika", "English/Reading": "English/Reading" }
};
function subjectLabel(name) {
  const lang = getLanguage();
  return (SUBJECT_LABELS[lang] && SUBJECT_LABELS[lang][name]) || name;
}

const TOPIC_LABELS = {
  en: { Biology: "Biology", Physics: "Physics", Geology: "Geology", Arithmetic: "Arithmetic", Algebra: "Algebra", Geometry: "Geometry", Literature: "Literature", Grammar: "Grammar" },
  tl: { Biology: "Biyolohiya", Physics: "Pisika", Geology: "Heolohiya", Arithmetic: "Aritmetika", Algebra: "Algebra", Geometry: "Geometriya", Literature: "Literature", Grammar: "Grammar" }
};
function topicLabel(key) {
  const lang = getLanguage();
  return (TOPIC_LABELS[lang] && TOPIC_LABELS[lang][key]) || key;
}

// ===== STATIC HTML AUTO-TRANSLATION =====
function applyStaticI18n() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
  });
  document.querySelectorAll("[data-i18n-html]").forEach(el => {
    el.innerHTML = t(el.getAttribute("data-i18n-html")).replace(/\n/g, "<br>");
  });
}
document.addEventListener("DOMContentLoaded", applyStaticI18n);

// ===== TAGALOG QUESTION BANK (Science/Math only; populated in Task 2) =====
const SCI_MATH_TOPICS = ["Biology", "Physics", "Geology", "Arithmetic", "Algebra", "Geometry"];
const FALLBACK_BANKS_TL = {};
