// ===== LANGUAGE STATE =====
function getLanguage() {
  return localStorage.getItem("selectedLanguage") === "tl" ? "tl" : "en";
}

function setLanguage(lang) {
  localStorage.setItem("selectedLanguage", lang === "tl" ? "tl" : "en");
}

// ===== UI STRINGS =====
const UI_STRINGS = {
  en: {
    login_tab_login: "Log In",
    login_tab_register: "Register",
    login_placeholder_username: "Username",
    login_placeholder_password: "Password",
    login_btn_submit_login: "Log In",
    login_btn_submit_register: "Register",
    login_or_divider: "— or —",
    login_btn_guest: "Play as Guest",
    login_err_missing_fields: "Enter a username and password.",
    login_err_username_taken: "That username is already taken.",
    login_err_wrong_credentials: "Incorrect username or password.",
    login_err_generic: "Something went wrong. Try again.",
    login_success_registered: "Account created! Log in below.",
    login_err_network: "Couldn't reach the server. Check your connection.",
    login_err_guest_missing: "Enter a username to play as guest.",

    menu_start: "Start Game",
    menu_characters: "Characters",
    menu_levels: "Levels",
    menu_ranks: "Ranks",
    menu_howtoplay: "How to Play",
    menu_logout: "Log Out",
    howtoplay_title: "📘 How to Play",
    howtoplay_body: "➤ Use arrow keys or on-screen buttons to move and jump.\n➤ Answer quiz questions correctly to progress through each level.\n➤ Finish all 3 levels of a topic to complete it.\n➤ More points makes you climb the ranks!",
    howtoplay_back: "Back to Menu",
    endscreen_title: "🏁 LEVEL COMPLETE!",
    endscreen_points_label: "Points:",
    endscreen_time_label: "Time:",
    endscreen_score_label: "Score:",
    endscreen_continue: "Continue",
    alert_choose_character: "Please choose a character first!",

    char_title: "Choose Your Character",
    char_confirm: "Confirm Character",
    char_back: "Back to Menu",
    char_msg_selected: "Character Selected!",
    char_msg_none: "Please select a character!",

    grade_title: "📚 Select Your Grade",
    grade_back: "⬅ Back",
    grade_7: "Grade 7",
    grade_8: "Grade 8",
    grade_9: "Grade 9",
    grade_10: "Grade 10",

    levelmap_back_main: "⬅ Main Menu",
    levelmap_back_subjects: "⬅ Subjects",
    levelmap_change_grade: "🎓 Change Grade",
    levelmap_select_subject: "Select Subject",

    levelselect_title: "🎮 Select Game Mode",
    levelselect_level1: "Level 1 — Platformer",
    levelselect_level2: "Level 2 — The Maze",
    levelselect_level3: "Level 3 — Flappy Flight",
    levelselect_back: "⬅ Back to Topics",

    hud_score_label: "Score:",
    hud_topic_label: "Topic:",
    summary_title: "Topic Complete!",
    summary_btn_mainmenu: "Main Menu",
    summary_btn_levelmap: "Level Map",
    summary_btn_ranks: "View Ranks",
    summary_btn_another: "Choose Another Topic",
    loading_text: "Loading questions...",
    error_title: "Couldn't load questions",
    error_body: "No offline questions exist for this topic yet. Check the Gemini API key/network and try again.",
    error_retry: "Retry",
    error_back: "Back to Topic Select",
    levelintro_go: "Go!",
    quiz_badge: "✨ Generated by Gemini",
    quiz_correct_feedback: "Correct! +{n} point(s)",
    quiz_wrong_feedback: "Wrong — correct answer highlighted.",
    quiz_continue: "Continue",
    levelintro_maze_text: "Answer questions to open the gates and find the exit! Correct answers are now worth {n} points each.",
    levelintro_flappy_text: "Tap or press Space to flap through the pipes! Correct answers are now worth {n} points each.",

    rank_title: "🏆 Leaderboard",
    rank_subtitle: "Top Players",
    rank_back: "⬅ Back"
  },
  tl: {
    login_tab_login: "Mag-log In",
    login_tab_register: "Magrehistro",
    login_placeholder_username: "Username",
    login_placeholder_password: "Password",
    login_btn_submit_login: "Mag-log In",
    login_btn_submit_register: "Magrehistro",
    login_or_divider: "— o —",
    login_btn_guest: "Maglaro bilang Bisita",
    login_err_missing_fields: "Maglagay ng username at password.",
    login_err_username_taken: "Nagamit na ang username na iyan.",
    login_err_wrong_credentials: "Maling username o password.",
    login_err_generic: "May nangyaring mali. Subukan muli.",
    login_success_registered: "Nagawa na ang account! Mag-log in sa ibaba.",
    login_err_network: "Hindi ma-reach ang server. Suriin ang iyong koneksyon.",
    login_err_guest_missing: "Maglagay ng username para maglaro bilang bisita.",

    menu_start: "Simulan ang Laro",
    menu_characters: "Mga Karakter",
    menu_levels: "Mga Level",
    menu_ranks: "Ranggo",
    menu_howtoplay: "Paano Maglaro",
    menu_logout: "Mag-log Out",
    howtoplay_title: "📘 Paano Maglaro",
    howtoplay_body: "➤ Gamitin ang arrow keys o mga on-screen button para gumalaw at tumalon.\n➤ Sagutin nang tama ang mga tanong para makasulong sa bawat level.\n➤ Tapusin ang lahat ng 3 level ng isang paksa para makumpleto ito.\n➤ Mas maraming puntos, mas mataas sa ranggo!",
    howtoplay_back: "Bumalik sa Menu",
    endscreen_title: "🏁 TAPOS NA ANG LEVEL!",
    endscreen_points_label: "Puntos:",
    endscreen_time_label: "Oras:",
    endscreen_score_label: "Iskor:",
    endscreen_continue: "Magpatuloy",
    alert_choose_character: "Pumili muna ng karakter!",

    char_title: "Piliin ang Iyong Karakter",
    char_confirm: "Kumpirmahin ang Karakter",
    char_back: "Bumalik sa Menu",
    char_msg_selected: "Napili ang Karakter!",
    char_msg_none: "Pumili ng karakter!",

    grade_title: "📚 Piliin ang Iyong Baitang",
    grade_back: "⬅ Bumalik",
    grade_7: "Baitang 7",
    grade_8: "Baitang 8",
    grade_9: "Baitang 9",
    grade_10: "Baitang 10",

    levelmap_back_main: "⬅ Pangunahing Menu",
    levelmap_back_subjects: "⬅ Mga Asignatura",
    levelmap_change_grade: "🎓 Baguhin ang Baitang",
    levelmap_select_subject: "Piliin ang Asignatura",

    levelselect_title: "🎮 Piliin ang Uri ng Laro",
    levelselect_level1: "Level 1 — Platformer",
    levelselect_level2: "Level 2 — Ang Labirinto",
    levelselect_level3: "Level 3 — Paglipad",
    levelselect_back: "⬅ Bumalik sa mga Paksa",

    hud_score_label: "Iskor:",
    hud_topic_label: "Paksa:",
    summary_title: "Tapos na ang Paksa!",
    summary_btn_mainmenu: "Pangunahing Menu",
    summary_btn_levelmap: "Mapa ng Level",
    summary_btn_ranks: "Tingnan ang Ranggo",
    summary_btn_another: "Pumili ng Ibang Paksa",
    loading_text: "Naglo-load ng mga tanong...",
    error_title: "Hindi ma-load ang mga tanong",
    error_body: "Wala pang offline na tanong para sa paksang ito. Suriin ang Gemini API key/koneksyon at subukan muli.",
    error_retry: "Subukan Muli",
    error_back: "Bumalik sa Pagpili ng Paksa",
    levelintro_go: "Sige!",
    quiz_badge: "✨ Ginawa ng Gemini",
    quiz_correct_feedback: "Tama! +{n} puntos",
    quiz_wrong_feedback: "Mali — naka-highlight ang tamang sagot.",
    quiz_continue: "Magpatuloy",
    levelintro_maze_text: "Sagutin ang mga tanong para mabuksan ang mga gate at mahanap ang labasan! Ang tamang sagot ay nagkakahalaga na ngayon ng {n} puntos bawat isa.",
    levelintro_flappy_text: "Pindutin o i-press ang Space para lumipad sa pagitan ng mga tubo! Ang tamang sagot ay nagkakahalaga na ngayon ng {n} puntos bawat isa.",

    rank_title: "🏆 Listahan ng mga Nangunguna",
    rank_subtitle: "Nangungunang mga Manlalaro",
    rank_back: "⬅ Bumalik"
  }
};

function t(key, vars) {
  const lang = getLanguage();
  let str = (UI_STRINGS[lang] && UI_STRINGS[lang][key]) || UI_STRINGS.en[key] || key;
  if (vars) {
    Object.keys(vars).forEach(k => { str = str.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]); });
  }
  return str;
}

// ===== SUBJECT / TOPIC DISPLAY LABELS (display only — never used as storage/lookup keys) =====
const SUBJECT_LABELS = {
  en: { "Science": "Science", "Math": "Math", "English/Reading": "English/Reading" },
  tl: { "Science": "Agham", "Math": "Matematika", "English/Reading": "English/Reading" }
};
function subjectLabel(name) {
  const lang = getLanguage();
  return (SUBJECT_LABELS[lang] && SUBJECT_LABELS[lang][name]) || name;
}

const TOPIC_LABELS = {
  en: { Biology: "Biology", Physics: "Physics", Geology: "Geology", Arithmetic: "Arithmetic", Algebra: "Algebra", Geometry: "Geometry", Literature: "Literature", Grammar: "Grammar" },
  tl: { Biology: "Biyolohiya", Physics: "Pisika", Geology: "Heolohiya", Arithmetic: "Aritmetika", Algebra: "Algebra", Geometry: "Geometriya", Literature: "Literature", Grammar: "Grammar" }
};
function topicLabel(key) {
  const lang = getLanguage();
  return (TOPIC_LABELS[lang] && TOPIC_LABELS[lang][key]) || key;
}

// ===== STATIC HTML AUTO-TRANSLATION =====
function applyStaticI18n() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
  });
  document.querySelectorAll("[data-i18n-html]").forEach(el => {
    el.innerHTML = t(el.getAttribute("data-i18n-html")).replace(/\n/g, "<br>");
  });
}
document.addEventListener("DOMContentLoaded", applyStaticI18n);

// ===== TAGALOG QUESTION BANK (Science/Math only; populated in Task 2) =====
const SCI_MATH_TOPICS = ["Biology", "Physics", "Geology", "Arithmetic", "Algebra", "Geometry"];
const FALLBACK_BANKS_TL = {
  Biology: {
    low: [
      { text: "Ano ang pangunahing organ na gumagawa ng gas exchange?", choices: ["Baga", "Bronkus", "Puso", "Trakea"], correct: 1, explain: "Sa baga nagaganap ang palitan ng oxygen at carbon dioxide sa pagitan ng hangin at dugo." },
      { text: "Anong organ ang nagbobomba ng dugo?", choices: ["Ugat", "Arterya", "Utak", "Puso"], correct: 4, explain: "Ang puso ang nagbobomba ng dugo papunta sa buong katawan sa pamamagitan ng pagkontrata nito." },
      { text: "Ano ang tawag sa iba't ibang anyo ng isang gene?", choices: ["Phenotype", "Genotype", "Alleles", "Punnett Square"], correct: 3, explain: "Ang alleles ay iba't ibang bersyon ng iisang gene na nagdedetermina ng katangian." },
      { text: "Ano ang biodiversity?", choices: ["Iba't ibang uri ng buhay na organismo", "Lugar na may invasive species", "Kung saan iisang species lang ang namumuno", "Komunidad na puro parehong hayop"], correct: 1, explain: "Tumutukoy ang biodiversity sa dami at iba't ibang uri ng buhay na organismo sa isang lugar." },
      { text: "Anong gas ang kailangan para sa photosynthesis?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 2, explain: "Ginagamit ng halaman ang carbon dioxide bilang sangkap sa paggawa ng pagkain sa photosynthesis." },
      { text: "Aling bahagi ng cell ang kumokontrol sa mga gawain nito?", choices: ["Nucleus", "Cell wall", "Cytoplasm", "Ribosome"], correct: 1, explain: "Ang nucleus ang naghahawak ng DNA at nagdidirekta sa lahat ng aktibidad ng cell." },
      { text: "Anong gas ang inilalabas ng halaman habang nagpo-photosynthesis?", choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Water vapor"], correct: 2, explain: "Bunga ng photosynthesis, inilalabas ng halaman ang oxygen bilang byproduct." },
      { text: "Aling blood cells ang tumutulong labanan ang impeksyon?", choices: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], correct: 2, explain: "Ang white blood cells ang nakikipaglaban sa mga bacteria at virus na pumapasok sa katawan." },
      { text: "Ano ang pinakamaliit na yunit ng buhay?", choices: ["Tissue", "Organ", "Cell", "Atom"], correct: 3, explain: "Ang cell ang pinakamaliit na bahagi ng katawan na maituturing nang buhay." },
      { text: "Aling organ ang bahagi ng digestive system?", choices: ["Baga", "Sikmura", "Puso", "Bato"], correct: 2, explain: "Ang sikmura ang nagtutunaw ng pagkain gamit ang acid bago ito ipasa sa bituka." },
      { text: "Ano ang tawag sa hayop na kumakain lang ng halaman?", choices: ["Carnivore", "Herbivore", "Omnivore", "Decomposer"], correct: 2, explain: "Ang herbivore ay hayop na halaman lamang ang kinakain, tulad ng kalabaw." },
      { text: "Aling bahagi ng halaman ang sumisipsip ng tubig mula sa lupa?", choices: ["Dahon", "Tangkay", "Ugat", "Bulaklak"], correct: 3, explain: "Ang ugat ang sumisipsip ng tubig at mineral mula sa lupa papunta sa buong halaman." },
      { text: "Anong gas ang kailangan ng tao para mabuhay?", choices: ["Carbon dioxide", "Oxygen", "Helium", "Hydrogen"], correct: 2, explain: "Kailangan ng katawan ang oxygen para sa paghinga at paggawa ng enerhiya sa cells." },
      { text: "Ano ang tawag sa berdeng pigment ng halaman?", choices: ["Melanin", "Chlorophyll", "Hemoglobin", "Keratin"], correct: 2, explain: "Ang chlorophyll ang berdeng pigment na sumisipsip ng liwanag ng araw para sa photosynthesis." },
      { text: "Aling body system ang kinabibilangan ng utak at nerbiyos?", choices: ["Respiratory", "Nervous", "Circulatory", "Digestive"], correct: 2, explain: "Bahagi ng nervous system ang utak at nerbiyos na nagpapadala ng mga signal sa katawan." }
    ],
    mid: [
      { text: "Ano ang tawag sa proseso ng paghahati ng cell papunta sa dalawang magkaparehong cell?", choices: ["Meiosis", "Mitosis", "Fertilization", "Fermentation"], correct: 2, explain: "Sa mitosis, naghahati ang isang cell papunta sa dalawang magkaparehong anak na cell." },
      { text: "Ano ang function ng mitochondria?", choices: ["Paggawa ng protina", "Paggawa ng enerhiya", "Pag-iimbak ng tubig", "Pagkontrol ng cell"], correct: 2, explain: "Ang mitochondria ang gumagawa ng ATP o enerhiya na ginagamit ng cell." },
      { text: "Anong uri ng reproduction ang gumagamit ng dalawang magulang?", choices: ["Asexual", "Sexual", "Binary fission", "Budding"], correct: 2, explain: "Sa sexual reproduction, nagsasama ang sex cells mula sa dalawang magulang para makabuo ng bagong organismo." },
      { text: "Ano ang tawag sa mga organismong gumagawa ng sariling pagkain?", choices: ["Consumer", "Producer", "Decomposer", "Predator"], correct: 2, explain: "Ang producer, tulad ng halaman, ay gumagawa ng sariling pagkain sa pamamagitan ng photosynthesis." },
      { text: "Aling bahagi ng dugo ang nagdadala ng oxygen?", choices: ["White blood cells", "Platelets", "Red blood cells", "Plasma"], correct: 3, explain: "May hemoglobin ang red blood cells na siyang nagdadala ng oxygen sa buong katawan." },
      { text: "Ano ang enzyme na tumutunaw ng starch sa bibig?", choices: ["Pepsin", "Amylase", "Lipase", "Trypsin"], correct: 2, explain: "Ang amylase sa laway ang nagsisimulang tumunaw ng starch habang nasa bibig pa lang ang pagkain." },
      { text: "Ano ang tawag sa isang organismo na may dalawang magkaparehong alleles para sa isang trait?", choices: ["Homozygous", "Heterozygous", "Hybrid", "Codominant"], correct: 1, explain: "Homozygous ang tawag kapag magkapareho ang dalawang alleles ng isang organismo para sa isang trait." },
      { text: "Anong sistema ang responsable sa paggawa ng hormones?", choices: ["Nervous system", "Endocrine system", "Skeletal system", "Muscular system"], correct: 2, explain: "Ang endocrine system ang gumagawa at naglalabas ng mga hormones sa katawan." },
      { text: "Ano ang tawag sa proseso ng paglipat ng tubig papunta sa hangin mula sa dahon?", choices: ["Respiration", "Transpiration", "Photosynthesis", "Absorption"], correct: 2, explain: "Sa transpiration, umaalis ang tubig bilang singaw mula sa mga stomata ng dahon." },
      { text: "Aling organelle ang tinatawag na \"power house\" ng cell?", choices: ["Nucleus", "Mitochondria", "Golgi body", "Vacuole"], correct: 2, explain: "Tinatawag na power house ang mitochondria dahil dito ginagawa ang karamihan ng enerhiya ng cell." },
      { text: "Ano ang tawag sa pagbabago ng species sa paglipas ng panahon?", choices: ["Adaptation", "Evolution", "Mutation", "Selection"], correct: 2, explain: "Ang evolution ay unti-unting pagbabago ng mga species sa mahabang panahon dahil sa natural selection." },
      { text: "Anong uri ng symbiosis ang parehong nakikinabang ang dalawang organismo?", choices: ["Parasitism", "Commensalism", "Mutualism", "Predation"], correct: 3, explain: "Sa mutualism, parehong nakikinabang ang dalawang organismong nagsasama." },
      { text: "Ano ang tawag sa panlabas na balat ng halaman na proteksyon?", choices: ["Epidermis", "Cortex", "Xylem", "Phloem"], correct: 1, explain: "Ang epidermis ang panlabas na layer ng halaman na nagpoprotekta rito." },
      { text: "Alin sa sumusunod ang unang antas ng classification (pinakamalaki)?", choices: ["Species", "Genus", "Kingdom", "Domain"], correct: 4, explain: "Ang Domain ang pinakamalaking at pinakamalawak na antas sa biological classification." },
      { text: "Ano ang tawag sa pagsasama ng sperm at egg cell?", choices: ["Mitosis", "Meiosis", "Fertilization", "Germination"], correct: 3, explain: "Tinatawag na fertilization ang pagsasama ng sperm at egg cell upang makabuo ng bagong organismo." }
    ],
    high: [
      { text: "Ano ang tawag sa DNA replication na nangyayari bago mag-mitosis?", choices: ["Interphase", "Prophase", "Metaphase", "Telophase"], correct: 1, explain: "Sa interphase nagaganap ang DNA replication bago pa magsimula ang aktwal na paghahati ng cell." },
      { text: "Ano ang tawag sa pagbabago ng DNA sequence?", choices: ["Mutation", "Mitosis", "Meiosis", "Translation"], correct: 1, explain: "Ang mutation ay pagbabago sa sequence ng DNA na maaaring magdulot ng bagong katangian." },
      { text: "Anong proseso ang gumagawa ng protina mula sa mRNA?", choices: ["Transcription", "Translation", "Replication", "Fermentation"], correct: 2, explain: "Sa translation, binabasa ng ribosome ang mRNA upang bumuo ng protina." },
      { text: "Ano ang tawag sa paglipat ng genetic information mula DNA papunta sa RNA?", choices: ["Translation", "Transcription", "Transduction", "Transformation"], correct: 2, explain: "Sa transcription, kinokopya ang impormasyon mula sa DNA patungo sa RNA." },
      { text: "Aling Punnett Square ratio ang inaasahan sa monohybrid cross (Aa x Aa)?", choices: ["1:2:1", "3:1", "9:3:3:1", "1:1"], correct: 2, explain: "Sa monohybrid cross na Aa x Aa, ang inaasahang ratio ng phenotype ay 3:1 pabor sa dominant trait." },
      { text: "Ano ang tawag sa pinakamaliit na yunit ng heredity?", choices: ["Chromosome", "Gene", "Allele", "Genome"], correct: 2, explain: "Ang gene ang pinakamaliit na yunit ng heredity na nagdadala ng impormasyon para sa isang katangian." },
      { text: "Anong bahagi ng neuron ang tumatanggap ng signal?", choices: ["Axon", "Dendrite", "Synapse", "Myelin sheath"], correct: 2, explain: "Ang dendrite ang bahagi ng neuron na tumatanggap ng signal mula sa ibang neuron." },
      { text: "Ano ang tawag sa proseso ng paggawa ng ATP na walang oxygen?", choices: ["Aerobic respiration", "Anaerobic respiration", "Photosynthesis", "Transpiration"], correct: 2, explain: "Sa anaerobic respiration, gumagawa ng ATP ang cell kahit walang oxygen na available." },
      { text: "Anong organ system ang kinabibilangan ng kidney at bladder?", choices: ["Digestive", "Excretory", "Respiratory", "Circulatory"], correct: 2, explain: "Bahagi ng excretory system ang kidney at bladder na siyang nag-aalis ng waste mula sa katawan." },
      { text: "Ano ang tawag sa relasyon kung saan nakikinabang ang isa habang nasasaktan ang isa?", choices: ["Mutualism", "Commensalism", "Parasitism", "Competition"], correct: 3, explain: "Sa parasitism, nakikinabang ang isang organismo habang nasasaktan ang isa pa." },
      { text: "Anong bahagi ng cell ang may pananagutan sa paggawa ng protina?", choices: ["Ribosome", "Nucleus", "Mitochondria", "Vacuole"], correct: 1, explain: "Ang ribosome ang gumagawa ng protina sa pamamagitan ng pagbasa ng mRNA." },
      { text: "Ano ang tawag sa dominante at recessive na alleles na parehong nagpapakita ng effect?", choices: ["Dominant", "Recessive", "Codominance", "Incomplete dominance"], correct: 3, explain: "Sa codominance, parehong nagpapakita ng epekto ang dominant at recessive alleles nang sabay." },
      { text: "Aling proseso ang gumagawa ng haploid cells para sa reproduction?", choices: ["Mitosis", "Meiosis", "Binary fission", "Budding"], correct: 2, explain: "Sa meiosis, nabubuo ang mga haploid cells tulad ng sperm at egg para sa reproduction." },
      { text: "Ano ang tawag sa buong genetic material ng isang organismo?", choices: ["Gene", "Genome", "Chromosome", "Genotype"], correct: 2, explain: "Ang genome ang tumutukoy sa kabuuan ng genetic material ng isang organismo." },
      { text: "Anong bahagi ng puso ang nagpapadala ng dugo papunta sa baga?", choices: ["Left ventricle", "Right ventricle", "Left atrium", "Right atrium"], correct: 2, explain: "Ang right ventricle ang nagpapadala ng dugo na may kaunting oxygen papunta sa baga." }
    ]
  },
  Physics: {
    low: [
      { text: "Ano ang tawag sa puwersang humihila sa mga bagay pababa sa Daigdig?", choices: ["Friction", "Gravity", "Magnetism", "Tension"], correct: 2, explain: "Ang gravity ang puwersang humihila sa lahat ng bagay patungo sa gitna ng Daigdig." },
      { text: "Ano ang yunit ng panukat ng puwersa (force)?", choices: ["Newton", "Joule", "Watt", "Pascal"], correct: 1, explain: "Ang Newton ang standard na yunit ng puwersa sa physics." },
      { text: "Ano ang tawag sa enerhiyang taglay ng gumagalaw na bagay?", choices: ["Potential energy", "Kinetic energy", "Thermal energy", "Chemical energy"], correct: 2, explain: "Ang kinetic energy ay enerhiyang taglay ng isang bagay dahil sa paggalaw nito." },
      { text: "Alin sa sumusunod ang HINDI isang estado ng bagay?", choices: ["Solid", "Liquid", "Gas", "Energy"], correct: 4, explain: "Ang energy ay hindi estado ng matter — ang solid, liquid, at gas lamang ang mga estado nito." },
      { text: "Ano ang tawag sa puwersang lumalaban sa paggalaw ng bagay sa ibabaw ng ibang bagay?", choices: ["Gravity", "Friction", "Tension", "Elasticity"], correct: 2, explain: "Ang friction ang puwersang pumipigil o nagpapabagal sa paggalaw ng dalawang ibabaw na magkadikit." },
      { text: "Ano ang yunit ng panukat ng enerhiya?", choices: ["Newton", "Watt", "Joule", "Ampere"], correct: 3, explain: "Ang Joule ang standard na yunit ng panukat ng enerhiya." },
      { text: "Aling makina ang gumagamit ng simpleng lever?", choices: ["Pulley", "Wedge", "Seesaw", "Screw"], correct: 3, explain: "Ang seesaw ay gumagamit ng lever principle kung saan may fulcrum sa gitna." },
      { text: "Ano ang tawag sa pagbabago ng estado mula solid papuntang liquid?", choices: ["Freezing", "Melting", "Evaporation", "Condensation"], correct: 2, explain: "Tinatawag na melting ang pagsasanib ng solid tungong liquid dahil sa init." },
      { text: "Ano ang tawag sa pagbabago ng estado mula gas papuntang liquid?", choices: ["Melting", "Freezing", "Condensation", "Evaporation"], correct: 3, explain: "Sa condensation, nagiging liquid ang gas dahil sa pagbaba ng temperatura." },
      { text: "Alin ang mabilis na dumadaloy na anyo ng enerhiya mula sa mainit papuntang malamig na bagay?", choices: ["Light", "Heat", "Sound", "Electricity"], correct: 2, explain: "Dumadaloy ang heat mula sa mainit patungo sa malamig na bagay hanggang magkapantay ang temperatura." },
      { text: "Ano ang tawag sa daan na tinatahak ng liwanag sa tuwid na linya?", choices: ["Reflection", "Refraction", "Rectilinear propagation", "Diffraction"], correct: 3, explain: "Tinatawag na rectilinear propagation ang katangian ng liwanag na dumadaloy sa tuwid na landas." },
      { text: "Ano ang tawag sa pagbaligtad ng liwanag sa isang salamin?", choices: ["Refraction", "Reflection", "Absorption", "Diffusion"], correct: 2, explain: "Sa reflection, tumatalbog ang liwanag pabalik matapos tamaan ang isang ibabaw tulad ng salamin." },
      { text: "Anong uri ng circuit ang may iisang daan lamang ang agos ng kuryente?", choices: ["Parallel circuit", "Series circuit", "Open circuit", "Short circuit"], correct: 2, explain: "Sa series circuit, iisa lang ang daanan ng agos kaya sunod-sunod dumadaloy ang kuryente." },
      { text: "Ano ang tawag sa panukat ng bilis ng paggalaw ng bagay?", choices: ["Acceleration", "Speed", "Force", "Mass"], correct: 2, explain: "Sinusukat ng speed kung gaano kabilis gumagalaw ang isang bagay sa isang tiyak na oras." },
      { text: "Alin sa sumusunod ang halimbawa ng simpleng makina?", choices: ["Cellphone", "Lever", "Computer", "Kotse"], correct: 2, explain: "Ang lever ay isang simpleng makina na gumagamit ng fulcrum para pagaanin ang trabaho." }
    ],
    mid: [
      { text: "Ano ang batas na nagsasabing \"Ang bawat aksyon ay may katumbas na reaksyon\"?", choices: ["Unang Batas ni Newton", "Ikalawang Batas ni Newton", "Ikatlong Batas ni Newton", "Batas ni Ohm"], correct: 3, explain: "Sinasabi ng Ikatlong Batas ni Newton na may katumbas at kabaligtaran na reaksyon ang bawat aksyon." },
      { text: "Ano ang formula ng puwersa ayon kay Newton?", choices: ["F=ma", "F=mv", "F=m/a", "F=at"], correct: 1, explain: "Ayon kay Newton, ang puwersa ay katumbas ng mass na pinarami sa acceleration, kaya F=ma." },
      { text: "Ano ang tawag sa likas na kalagayan ng bagay na tumutol sa pagbabago ng galaw?", choices: ["Momentum", "Inertia", "Velocity", "Acceleration"], correct: 2, explain: "Ang inertia ang katangian ng bagay na tumutol sa anumang pagbabago sa kanyang kalagayan ng galaw." },
      { text: "Ano ang yunit ng panukat ng electric current?", choices: ["Volt", "Watt", "Ampere", "Ohm"], correct: 3, explain: "Ang Ampere ang yunit na ginagamit sa pagsukat ng electric current." },
      { text: "Ano ang batas na nag-uugnay sa voltage, current, at resistance?", choices: ["Batas ni Newton", "Batas ni Ohm", "Batas ni Boyle", "Batas ni Coulomb"], correct: 2, explain: "Sinasabi ng Batas ni Ohm na ang voltage ay katumbas ng current na pinarami sa resistance." },
      { text: "Ano ang tawag sa enerhiyang nakaimbak dahil sa posisyon ng bagay?", choices: ["Kinetic energy", "Potential energy", "Thermal energy", "Sound energy"], correct: 2, explain: "Ang potential energy ay enerhiyang nakaimbak dahil sa posisyon o taas ng isang bagay." },
      { text: "Ano ang tawag sa dami ng bagay (matter) na taglay ng isang bagay?", choices: ["Weight", "Mass", "Volume", "Density"], correct: 2, explain: "Ang mass ang sumusukat sa dami ng matter na bumubuo sa isang bagay." },
      { text: "Ano ang pagkakaiba ng bigat (weight) sa mass?", choices: ["Pareho lang sila", "Ang bigat ay nakadepende sa gravity", "Ang mass ay nagbabago sa iba't ibang planeta", "Walang pagkakaiba"], correct: 2, explain: "Nagbabago ang bigat depende sa gravity ng lugar, samantalang pareho ang mass kahit saan." },
      { text: "Ano ang tawag sa paggalaw pabalik-balik sa parehong daan?", choices: ["Circular motion", "Oscillatory motion", "Projectile motion", "Linear motion"], correct: 2, explain: "Sa oscillatory motion, paulit-ulit na pabalik-balik ang galaw sa parehong landas, tulad ng pendulum." },
      { text: "Alin ang yunit ng panukat ng presyon?", choices: ["Pascal", "Joule", "Newton", "Watt"], correct: 1, explain: "Ang Pascal ang standard na yunit ng panukat ng presyon." },
      { text: "Ano ang tawag sa init na kailangan para mabago ang estado ng bagay nang hindi nagbabago ang temperatura?", choices: ["Specific heat", "Latent heat", "Kinetic heat", "Radiant heat"], correct: 2, explain: "Ang latent heat ang init na ginagamit para magbago ng estado ang bagay nang hindi tumataas ang temperatura nito." },
      { text: "Anong uri ng alon ang tunog (sound)?", choices: ["Transverse wave", "Longitudinal wave", "Electromagnetic wave", "Standing wave"], correct: 2, explain: "Ang tunog ay longitudinal wave dahil pabalik-balik ang direksyon ng vibration kaugnay ng direksyon ng paglaganap." },
      { text: "Ano ang tawag sa paggalaw ng bagay na pabilog?", choices: ["Linear motion", "Circular motion", "Projectile motion", "Random motion"], correct: 2, explain: "Ang circular motion ay paggalaw ng bagay sa isang landas na hugis bilog." },
      { text: "Anong instrumento ang ginagamit para sukatin ang electric current?", choices: ["Voltmeter", "Ammeter", "Thermometer", "Barometer"], correct: 2, explain: "Ginagamit ang ammeter para direktang sukatin ang electric current sa isang circuit." },
      { text: "Ano ang tawag sa puwersang kumakabig sa dalawang bagay dahil sa kanilang mass?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correct: 2, explain: "Ang gravity ang puwersang kumakabig sa dalawang bagay dahil sa kanilang mass, kahit malayo sila sa isa't isa." }
    ],
    high: [
      { text: "Ano ang batas na nagsasabing hindi nawawala ang enerhiya, nagbabagong anyo lamang?", choices: ["Batas ng Konserbasyon ng Masa", "Batas ng Konserbasyon ng Enerhiya", "Batas ni Newton", "Batas ni Ohm"], correct: 2, explain: "Ayon sa Batas ng Konserbasyon ng Enerhiya, hindi nawawala ang enerhiya kundi nagbabagong-anyo lamang ito." },
      { text: "Ano ang tawag sa pinakamaliit na yunit ng element na may katangian pa rin nito?", choices: ["Molecule", "Atom", "Proton", "Electron"], correct: 2, explain: "Ang atom ang pinakamaliit na bahagi ng element na nagtataglay pa rin ng katangian nito." },
      { text: "Ano ang tawag sa pagbabago ng liwanag habang dumaraan sa ibang medium?", choices: ["Reflection", "Refraction", "Diffraction", "Absorption"], correct: 2, explain: "Sa refraction, yumuyuko ang liwanag kapag ito ay dumadaan mula sa isang medium papunta sa iba." },
      { text: "Ano ang tawag sa pagsasama ng dalawang atomic nuclei na naglalabas ng malaking enerhiya?", choices: ["Fission", "Fusion", "Ionization", "Radiation"], correct: 2, explain: "Sa fusion, nagsasama ang dalawang atomic nuclei at naglalabas ng napakalaking enerhiya, gaya ng sa araw." },
      { text: "Ano ang tawag sa paghahati ng atomic nucleus na naglalabas ng enerhiya?", choices: ["Fusion", "Fission", "Combustion", "Oxidation"], correct: 2, explain: "Sa fission, naghahati ang isang malaking atomic nucleus at naglalabas ng enerhiya." },
      { text: "Alin sa sumusunod ang particle na may negatibong charge?", choices: ["Proton", "Neutron", "Electron", "Nucleus"], correct: 3, explain: "Ang electron ang particle na may negatibong charge na umiikot sa nucleus ng atom." },
      { text: "Ano ang tawag sa dalas ng alon bawat segundo?", choices: ["Wavelength", "Frequency", "Amplitude", "Period"], correct: 2, explain: "Sinusukat ng frequency kung ilang beses umuulit ang isang alon sa loob ng isang segundo." },
      { text: "Ano ang yunit ng panukat ng frequency?", choices: ["Meter", "Hertz", "Second", "Newton"], correct: 2, explain: "Ang Hertz ang yunit na ginagamit para sukatin ang frequency ng isang alon." },
      { text: "Ano ang tawag sa distansya sa pagitan ng dalawang magkatabing crest ng alon?", choices: ["Amplitude", "Frequency", "Wavelength", "Period"], correct: 3, explain: "Ang wavelength ang distansya sa pagitan ng dalawang magkasunod na crest ng isang alon." },
      { text: "Ano ang tawag sa spectrum ng liwanag na nakikita ng mata?", choices: ["Ultraviolet", "Infrared", "Visible light", "X-ray"], correct: 3, explain: "Ang visible light ang bahagi lamang ng electromagnetic spectrum na nakikita ng mata ng tao." },
      { text: "Anong batas ang nagsasabing ang presyon at volume ng gas ay inversely proportional sa constant na temperatura?", choices: ["Batas ni Boyle", "Batas ni Charles", "Batas ni Newton", "Batas ni Ohm"], correct: 1, explain: "Sinasabi ng Batas ni Boyle na inversely proportional ang presyon at volume ng gas kapag pare-pareho ang temperatura." },
      { text: "Ano ang tawag sa paglipat ng init nang walang direktang contact?", choices: ["Conduction", "Convection", "Radiation", "Insulation"], correct: 3, explain: "Sa radiation, naglalakbay ang init sa anyo ng waves kahit walang direktang contact o medium." },
      { text: "Ano ang tawag sa paglipat ng init sa pamamagitan ng galaw ng likido o gas?", choices: ["Conduction", "Convection", "Radiation", "Diffusion"], correct: 2, explain: "Sa convection, gumagalaw ang init kasabay ng galaw ng likido o gas." },
      { text: "Ano ang tawag sa paglipat ng init sa pamamagitan ng direktang contact?", choices: ["Conduction", "Convection", "Radiation", "Insulation"], correct: 1, explain: "Sa conduction, dumadaloy ang init sa pamamagitan ng direktang contact ng mga particle ng bagay." },
      { text: "Ano ang tawag sa panukat ng inertia ng isang bagay habang gumagalaw?", choices: ["Weight", "Momentum", "Force", "Pressure"], correct: 2, explain: "Sinusukat ng momentum ang inertia ng isang gumagalaw na bagay batay sa mass at velocity nito." }
    ]
  },
  Geology: {
    low: [
      { text: "Ano ang tawag sa panlabas na patong ng Daigdig?", choices: ["Core", "Mantle", "Crust", "Atmosphere"], correct: 3, explain: "Ang crust ang pinakalabas at pinakamanipis na layer ng Daigdig kung saan tayo naninirahan." },
      { text: "Ilan ang layer ng Daigdig?", choices: ["2", "3", "4", "5"], correct: 3, explain: "May apat na layer ang Daigdig: crust, mantle, outer core, at inner core." },
      { text: "Ano ang tawag sa uri ng bato na nabuo mula sa pagtigas ng magma?", choices: ["Sedimentary", "Igneous", "Metamorphic", "Mineral"], correct: 2, explain: "Ang igneous rock ay nabubuo kapag tumigas ang magma o lava." },
      { text: "Ano ang tawag sa uri ng bato na nabuo sa pamamagitan ng compaction ng sediments?", choices: ["Igneous", "Sedimentary", "Metamorphic", "Fossil"], correct: 2, explain: "Ang sedimentary rock ay nabubuo kapag nagkumpol at natambak ang mga sediment sa paglipas ng panahon." },
      { text: "Ano ang tawag sa uri ng bato na nabago dahil sa init at presyon?", choices: ["Igneous", "Sedimentary", "Metamorphic", "Mineral"], correct: 3, explain: "Nagiging metamorphic rock ang isang bato kapag nabago ang anyo nito dahil sa matinding init at presyon." },
      { text: "Ano ang tawag sa pagguho ng lupa at bato dahil sa ulan at hangin?", choices: ["Erosion", "Deposition", "Weathering", "Sedimentation"], correct: 3, explain: "Ang weathering ay ang unti-unting pagkasira ng bato dahil sa ulan, hangin, at iba pang elemento." },
      { text: "Ano ang tawag sa panginginig ng lupa dahil sa biglaang paglabas ng enerhiya?", choices: ["Volcano", "Earthquake", "Tsunami", "Landslide"], correct: 2, explain: "Ang earthquake ay panginginig ng lupa dahil sa biglaang paglabas ng enerhiya mula sa loob ng Daigdig." },
      { text: "Ano ang tawag sa bundok na naglalabas ng lava at abo?", choices: ["Earthquake", "Volcano", "Glacier", "Fault"], correct: 2, explain: "Ang volcano ay bundok na naglalabas ng lava, abo, at gas mula sa loob ng Daigdig." },
      { text: "Ano ang tinatawag na natural na yamang mineral na pinagmumulan ng metal?", choices: ["Rock", "Ore", "Soil", "Fossil"], correct: 2, explain: "Ang ore ay bato na naglalaman ng sapat na metal para makuha at magamit ito." },
      { text: "Ano ang tawag sa likidong tunaw na bato sa ilalim ng Daigdig?", choices: ["Lava", "Magma", "Ash", "Mineral"], correct: 2, explain: "Ang magma ang tawag sa tunaw na bato habang nasa ilalim pa ito ng Daigdig." },
      { text: "Ano ang tawag sa likidong tunaw na bato na lumabas na sa ibabaw ng Daigdig?", choices: ["Magma", "Lava", "Ash", "Sediment"], correct: 2, explain: "Kapag umahon na ang magma sa ibabaw ng Daigdig, tinatawag na itong lava." },
      { text: "Anong layer ng Daigdig ang may pinakamataas na temperatura?", choices: ["Crust", "Mantle", "Outer core", "Inner core"], correct: 4, explain: "Ang inner core ang may pinakamataas na temperatura dahil ito ang pinakamalapit sa gitna ng Daigdig." },
      { text: "Ano ang tawag sa proseso ng pag-ipon ng sediments sa isang lugar?", choices: ["Erosion", "Weathering", "Deposition", "Melting"], correct: 3, explain: "Ang deposition ay ang pag-iipon ng mga natangay na sediment sa isang bagong lugar." },
      { text: "Ano ang tawag sa bahagi ng crust na gumagalaw at nagdudulot ng lindol?", choices: ["Plate", "Fault", "Layer", "Core"], correct: 2, explain: "Ang fault ay bitak sa crust kung saan gumagalaw ang bato at nagdudulot ng lindol." },
      { text: "Ilan ang major tectonic plates sa Daigdig?", choices: ["3", "5", "7", "10"], correct: 3, explain: "May pitong major tectonic plates na bumubuo sa panlabas na layer ng Daigdig." }
    ],
    mid: [
      { text: "Ano ang tawag sa teorya na ang mga kontinente ay dating nagkakadikit?", choices: ["Plate tectonics", "Continental drift", "Big bang theory", "Erosion theory"], correct: 2, explain: "Ayon sa continental drift, nagkadikit dating ang mga kontinente bago ito naghiwa-hiwalay." },
      { text: "Ano ang tawag sa hangganan kung saan naghihiwalay ang dalawang tectonic plate?", choices: ["Convergent boundary", "Divergent boundary", "Transform boundary", "Fault line"], correct: 2, explain: "Sa divergent boundary, humihiwalay ang dalawang plate mula sa isa't isa." },
      { text: "Ano ang tawag sa hangganan kung saan nagbabanggaan ang dalawang tectonic plate?", choices: ["Divergent boundary", "Convergent boundary", "Transform boundary", "Rift zone"], correct: 2, explain: "Sa convergent boundary, nagtatagpo o nagbabanggaan ang dalawang plate." },
      { text: "Ano ang tawag sa hangganan kung saan nagdudulasan ang dalawang plate nang pahalang?", choices: ["Convergent boundary", "Divergent boundary", "Transform boundary", "Subduction zone"], correct: 3, explain: "Sa transform boundary, nagdudulasan nang pahalang ang dalawang plate laban sa isa't isa." },
      { text: "Ano ang tawag sa proseso kung saan isang plate ay pumapasok sa ilalim ng isa pang plate?", choices: ["Subduction", "Rifting", "Uplift", "Folding"], correct: 1, explain: "Sa subduction, pumapasok ang isang plate sa ilalim ng isa pang plate patungo sa mantle." },
      { text: "Ano ang tawag sa panukat ng lakas ng lindol?", choices: ["Barometer scale", "Richter scale", "Beaufort scale", "pH scale"], correct: 2, explain: "Ginagamit ang Richter scale para sukatin ang lakas o magnitude ng isang lindol." },
      { text: "Ano ang tawag sa siklo ng pagbabago ng bato mula sa isang uri patungo sa iba?", choices: ["Water cycle", "Rock cycle", "Carbon cycle", "Nitrogen cycle"], correct: 2, explain: "Ang rock cycle ang naglalarawan sa patuloy na pagbabago ng bato mula igneous, sedimentary, hanggang metamorphic." },
      { text: "Ano ang tawag sa mineral na bumubuo sa karamihan ng bato?", choices: ["Ore", "Rock-forming mineral", "Fossil", "Sediment"], correct: 2, explain: "Ang rock-forming mineral ang mga mineral na bumubuo sa pinakamalaking bahagi ng mga bato." },
      { text: "Anong layer ng Daigdig ang solid at gawa sa iron at nickel?", choices: ["Outer core", "Inner core", "Mantle", "Crust"], correct: 2, explain: "Ang inner core ay solid at gawa sa iron at nickel dahil sa matinding presyon kahit napakainit nito." },
      { text: "Anong layer ng Daigdig ang likido at gawa rin sa iron at nickel?", choices: ["Inner core", "Outer core", "Mantle", "Crust"], correct: 2, explain: "Ang outer core ay likido dahil mas mababa ang presyon dito kumpara sa inner core, kahit magkatulad ang materyales." },
      { text: "Ano ang tawag sa malaking bahagi ng lupa na nakapaligid sa Daigdig?", choices: ["Atmosphere", "Lithosphere", "Hydrosphere", "Biosphere"], correct: 2, explain: "Ang lithosphere ang matigas na panlabas na bahagi ng Daigdig na binubuo ng crust at itaas na mantle." },
      { text: "Ano ang tawag sa pag-aaral ng mga fossil?", choices: ["Geology", "Paleontology", "Biology", "Archaeology"], correct: 2, explain: "Ang paleontology ang agham na nag-aaral ng mga fossil at sinaunang buhay." },
      { text: "Ano ang tawag sa mineral na may crystal structure na maaaring makita sa bato?", choices: ["Ore", "Sediment", "Crystal", "Fossil"], correct: 3, explain: "Ang crystal ay mineral na may regular at maayos na hugis o structure na makikita sa loob ng bato." },
      { text: "Anong bagay ang nagbibigay ng ebidensya sa nakaraang buhay sa Daigdig?", choices: ["Mineral", "Fossil", "Magma", "Lava"], correct: 2, explain: "Ang fossil ang nagsisilbing ebidensya ng mga organismong nabuhay noong nakaraan." },
      { text: "Ano ang tawag sa proseso ng pagbuo ng bagong crust sa gitna ng dagat?", choices: ["Subduction", "Sea floor spreading", "Weathering", "Erosion"], correct: 2, explain: "Sa sea floor spreading, bumubuo ng bagong crust habang humihiwalay ang mga plate sa ilalim ng dagat." }
    ],
    high: [
      { text: "Ano ang tawag sa paraang ginagamit para sukatin ang edad ng bato gamit ang radioactive decay?", choices: ["Relative dating", "Radiometric dating", "Carbon cycle dating", "Stratigraphy"], correct: 2, explain: "Ginagamit ang radiometric dating para tantiyahin ang edad ng bato batay sa rate ng radioactive decay." },
      { text: "Ano ang tawag sa prinsipyo na ang mas matandang layer ng bato ay nasa ilalim?", choices: ["Law of superposition", "Law of uniformitarianism", "Law of original horizontality", "Law of cross-cutting relationships"], correct: 1, explain: "Ayon sa Law of superposition, nasa ilalim ang mas matandang layer ng bato dahil una itong natambak." },
      { text: "Ano ang half-life ng isang radioactive element?", choices: ["Ang buong buhay nito", "Ang panahon para mabawasan ng kalahati ang dami nito", "Ang temperatura kung saan natutunaw ito", "Ang bigat nito"], correct: 2, explain: "Ang half-life ay ang oras na kailangan para mabawasan nang kalahati ang orihinal na dami ng radioactive element." },
      { text: "Ano ang tawag sa teoryang nagsasabing ang mga proseso ngayon ay pareho noong nakaraan?", choices: ["Catastrophism", "Uniformitarianism", "Continental drift", "Plate tectonics"], correct: 2, explain: "Ayon sa Uniformitarianism, ang mga geologic na proseso ngayon ay pareho rin noong sinaunang panahon." },
      { text: "Anong uri ng fault ang nagdudulot ng paggalaw pababa ng isang bahagi ng lupa?", choices: ["Normal fault", "Reverse fault", "Strike-slip fault", "Thrust fault"], correct: 1, explain: "Sa normal fault, gumagalaw pababa ang isang bahagi ng lupa dahil sa tension o pag-uunat." },
      { text: "Anong uri ng fault ang nagdudulot ng paggalaw pataas ng isang bahagi ng lupa dahil sa compression?", choices: ["Normal fault", "Reverse fault", "Strike-slip fault", "Divergent fault"], correct: 2, explain: "Sa reverse fault, gumagalaw pataas ang isang bahagi ng lupa dahil sa compression o pagtutulakan." },
      { text: "Ano ang tawag sa panukat ng epekto ng lindol batay sa pinsala?", choices: ["Richter scale", "Moment magnitude scale", "Mercalli scale", "Beaufort scale"], correct: 3, explain: "Ang Mercalli scale ang sumusukat sa epekto o pinsala ng lindol batay sa naramdaman at nakita." },
      { text: "Ano ang tawag sa layer ng Daigdig na kinaroroonan ng convection current na nagpapagalaw sa mga plate?", choices: ["Crust", "Mantle", "Outer core", "Inner core"], correct: 2, explain: "Sa mantle nagaganap ang convection current na siyang nagtutulak sa paggalaw ng mga tectonic plate." },
      { text: "Ano ang epekto ng convection current sa mantle sa mga tectonic plate?", choices: ["Pinapatigil ang paggalaw", "Nagiging dahilan ng paggalaw", "Walang epekto", "Ginagawang matigas ang plate"], correct: 2, explain: "Ang convection current sa mantle ang nagiging dahilan ng paggalaw ng mga tectonic plate sa itaas nito." },
      { text: "Ano ang tawag sa bulkan na maaari pang sumabog sa hinaharap?", choices: ["Extinct volcano", "Dormant volcano", "Active volcano", "Fossil volcano"], correct: 3, explain: "Ang active volcano ay bulkan na kasalukuyang o maaaring pang sumabog sa hinaharap." },
      { text: "Ano ang tawag sa bulkan na hindi na inaasahang sumabog pa?", choices: ["Active volcano", "Dormant volcano", "Extinct volcano", "Shield volcano"], correct: 3, explain: "Ang extinct volcano ay bulkan na hindi na inaasahang sumabog pa dahil wala nang magma supply." },
      { text: "Anong uri ng bato ang bumubuo sa Ring of Fire dahil sa maraming volcanic activity?", choices: ["Sedimentary", "Igneous", "Metamorphic", "Mineral"], correct: 2, explain: "Dominante ang igneous rock sa Ring of Fire dahil ito ay bunga ng maraming volcanic activity." },
      { text: "Ano ang tawag sa pagsukat ng oras batay sa pagkakapatong-patong ng mga layer ng bato?", choices: ["Stratigraphy", "Paleontology", "Radiometric dating", "Seismology"], correct: 1, explain: "Ang stratigraphy ang pag-aaral ng pagkakapatong-patong ng mga layer ng bato para tantiyahin ang oras." },
      { text: "Ano ang tawag sa agham na nag-aaral ng mga lindol?", choices: ["Volcanology", "Seismology", "Geology", "Meteorology"], correct: 2, explain: "Ang seismology ang sangay ng agham na nakatuon sa pag-aaral ng mga lindol." },
      { text: "Ano ang tawag sa agham na nag-aaral ng mga bulkan?", choices: ["Seismology", "Volcanology", "Geology", "Meteorology"], correct: 2, explain: "Ang volcanology ang sangay ng agham na nag-aaral ng mga bulkan at kanilang aktibidad." }
    ]
  },
  Arithmetic: {
    low: [
      { text: "Ano ang sagot sa 15 + 27?", choices: ["42", "32", "41", "40"], correct: 1, explain: "Ang 15 kapag idinagdag sa 27 ay nagiging 42." },
      { text: "Ano ang sagot sa 9 x 8?", choices: ["72", "63", "81", "64"], correct: 1, explain: "Ang 9 kapag pinarami ng 8 ay nagbibigay ng 72." },
      { text: "Ano ang sagot sa 144 ÷ 12?", choices: ["11", "12", "13", "14"], correct: 2, explain: "Ang 144 kapag hinati sa 12 ay nagiging 12 dahil 12 x 12 = 144." },
      { text: "Alin sa sumusunod ang prime number?", choices: ["4", "6", "7", "9"], correct: 3, explain: "Ang 7 ay prime number dahil ang tanging factors nito ay 1 at ang sarili nito." },
      { text: "Ano ang GCF ng 12 at 18?", choices: ["3", "6", "9", "12"], correct: 2, explain: "Ang 6 ang pinakamalaking numerong pareho pang naghahati sa 12 at 18." },
      { text: "Ano ang LCM ng 4 at 6?", choices: ["8", "10", "12", "24"], correct: 3, explain: "Ang 12 ang pinakamaliit na numero na parehong multiple ng 4 at 6." },
      { text: "Ano ang 3/4 kapag ginawang decimal?", choices: ["0.34", "0.75", "0.43", "0.25"], correct: 2, explain: "Kapag hinati ang 3 sa 4, ang resulta ay 0.75." },
      { text: "Ano ang 25% ng 200?", choices: ["25", "50", "75", "100"], correct: 2, explain: "Ang 25% ng 200 ay 50 dahil ika-apat na bahagi ito ng 200." },
      { text: "Alin ang tamang pagkakasunod mula pinakamaliit?", choices: ["1/4, 1/2, 3/4", "1/2, 1/4, 3/4", "3/4, 1/2, 1/4", "1/4, 3/4, 1/2"], correct: 1, explain: "Pinakamaliit ang 1/4, sinusundan ng 1/2, at pinakamalaki ang 3/4." },
      { text: "Ano ang sagot sa -5 + 8?", choices: ["-13", "3", "-3", "13"], correct: 2, explain: "Kapag idinagdag ang 8 sa -5, ang sagot ay 3." },
      { text: "Ano ang sagot sa 7 - (-3)?", choices: ["4", "10", "-10", "-4"], correct: 2, explain: "Ang pagbawas ng negatibong numero ay katumbas ng pagdadagdag, kaya 7-(-3)=7+3=10." },
      { text: "Ano ang tawag sa numerong hindi na mahahati pa maliban sa 1 at sa sarili nito?", choices: ["Composite number", "Prime number", "Whole number", "Integer"], correct: 2, explain: "Ang prime number ay numerong ang tanging factors ay 1 at ang sarili lamang nito." },
      { text: "Ano ang sagot sa 6²?", choices: ["12", "36", "24", "18"], correct: 2, explain: "Ang 6² ay 6 na pinarami sa sarili nito, kaya 6x6=36." },
      { text: "Ano ang square root ng 81?", choices: ["7", "8", "9", "10"], correct: 3, explain: "Ang square root ng 81 ay 9 dahil 9x9=81." },
      { text: "Ano ang sagot sa 2 + 3 x 4 gamit ang PEMDAS?", choices: ["20", "14", "24", "9"], correct: 2, explain: "Sa PEMDAS, unahin ang multiplication (3x4=12) bago idagdag ang 2, kaya 2+12=14." }
    ],
    mid: [
      { text: "Ano ang sagot kung i-solve ang 2x + 5 = 15?", choices: ["x=5", "x=10", "x=7", "x=4"], correct: 1, explain: "Ibawas ang 5 sa magkabilang panig (2x=10) tapos hatiin sa 2 para makuha ang x=5." },
      { text: "Ano ang sagot sa 3(x - 2) = 12?", choices: ["x=4", "x=6", "x=8", "x=2"], correct: 2, explain: "Hatiin ang 12 sa 3 para makuha ang x-2=4, dagdagan ng 2 para makuha ang x=6." },
      { text: "Paano isulat ang 0.05 bilang porsyento?", choices: ["0.5%", "5%", "50%", "0.05%"], correct: 2, explain: "Ang 0.05 kapag pinarami ng 100 ay nagiging 5%." },
      { text: "Ano ang ratio ng 4 sa 12 sa pinakasimpleng anyo?", choices: ["1:2", "1:3", "1:4", "2:3"], correct: 2, explain: "Hatiin ang 4 at 12 sa kanilang GCF na 4 para makuha ang 1:3." },
      { text: "Kung 3 apples ang halagang ₱30, magkano ang 7 apples?", choices: ["₱60", "₱70", "₱80", "₱90"], correct: 2, explain: "Kung ₱10 ang bawat apple (30÷3), ang 7 apples ay 7x10=₱70." },
      { text: "Ano ang sagot sa (-4) x (-6)?", choices: ["-24", "24", "-10", "10"], correct: 2, explain: "Ang negatibong numero na pinarami sa negatibo ay nagiging positibo, kaya (-4)x(-6)=24." },
      { text: "Ano ang absolute value ng -15?", choices: ["-15", "0", "15", "1"], correct: 3, explain: "Ang absolute value ay ang distansya mula sa zero anuman ang sign, kaya ang -15 ay 15." },
      { text: "Ano ang sagot sa 2/3 + 1/6?", choices: ["3/9", "5/6", "1/2", "1"], correct: 2, explain: "Gawing 4/6 ang 2/3, idagdag sa 1/6 para makuha ang 5/6." },
      { text: "Ano ang sagot sa 5/8 x 4/5?", choices: ["1/2", "9/13", "20/40", "4/5"], correct: 1, explain: "Paramihin ang numerators at denominators (20/40), na kapag pinasimple ay 1/2." },
      { text: "Ano ang tawag sa numerong maaaring isulat bilang fraction?", choices: ["Irrational number", "Rational number", "Whole number", "Natural number"], correct: 2, explain: "Ang rational number ay anumang numerong maisusulat bilang fraction ng dalawang integer." },
      { text: "Ano ang sagot sa 3² + 4²?", choices: ["25", "49", "12", "7"], correct: 1, explain: "3²=9 at 4²=16, kaya kapag idinagdag ang 9+16 ay 25." },
      { text: "Anong porsyento ang 3/4?", choices: ["34%", "75%", "43%", "50%"], correct: 2, explain: "Ang 3/4 kapag ginawang porsyento ay 75% dahil 3÷4=0.75." },
      { text: "Ano ang sagot sa 100 - 15% ng 100?", choices: ["15", "85", "90", "75"], correct: 2, explain: "Ang 15% ng 100 ay 15, kaya 100-15=85." },
      { text: "Kung ang exchange rate ay $1 = ₱56, magkano ang $10 sa piso?", choices: ["₱506", "₱560", "₱56", "₱650"], correct: 2, explain: "Kapag pinarami ang 56 sa 10, ang resulta ay ₱560." },
      { text: "Ano ang sagot sa 2³ x 2²?", choices: ["2⁵", "2⁶", "4⁵", "2¹"], correct: 1, explain: "Kapag pinaramihan ang parehong base, idinadagdag ang exponents, kaya 2³x2²=2⁵." }
    ],
    high: [
      { text: "Ano ang sagot sa √144?", choices: ["11", "12", "13", "14"], correct: 2, explain: "Ang square root ng 144 ay 12 dahil 12x12=144." },
      { text: "Ano ang sagot sa 2⁴?", choices: ["8", "16", "32", "4"], correct: 2, explain: "Ang 2⁴ ay 2x2x2x2 na katumbas ng 16." },
      { text: "Paano isulat ang 3,400,000 sa scientific notation?", choices: ["3.4 x 10⁵", "3.4 x 10⁶", "34 x 10⁵", "3.4 x 10⁷"], correct: 2, explain: "Ang 3,400,000 kapag isinulat sa scientific notation ay 3.4 x 10⁶ dahil anim na hakbang ang paglipat ng decimal." },
      { text: "Ano ang sagot sa log₁₀(1000)?", choices: ["1", "2", "3", "10"], correct: 3, explain: "Ang log₁₀(1000) ay 3 dahil 10³=1000." },
      { text: "Ano ang sagot sa 5! (5 factorial)?", choices: ["20", "100", "120", "60"], correct: 3, explain: "Ang 5! ay 5x4x3x2x1 na katumbas ng 120." },
      { text: "Ano ang sagot sa (3/4) ÷ (1/2)?", choices: ["3/8", "3/2", "6/4", "1/2"], correct: 2, explain: "Sa paghahati ng fraction, i-multiply sa reciprocal, kaya (3/4)x(2/1)=3/2." },
      { text: "Kung ang simple interest rate ay 5% sa ₱10,000 sa loob ng 2 taon, magkano ang interes?", choices: ["₱500", "₱1,000", "₱1,500", "₱2,000"], correct: 2, explain: "Ang simple interest ay principal x rate x time, kaya 10,000x0.05x2=₱1,000." },
      { text: "Ano ang sagot sa -3² (kung ang negative ay kasama sa base)?", choices: ["9", "-9", "6", "-6"], correct: 2, explain: "Dahil naunang i-square ang 3 bago ilapat ang negative sign sa karaniwang convention, ang -3² ay -9." },
      { text: "Ano ang sagot sa √2 kapag pinaikli sa dalawang decimal place?", choices: ["1.41", "1.42", "1.51", "1.61"], correct: 1, explain: "Ang square root ng 2 ay humigit-kumulang 1.41421, na pag-rounded sa dalawang decimal place ay 1.41." },
      { text: "Anong uri ng numero ang π (pi)?", choices: ["Rational number", "Irrational number", "Whole number", "Integer"], correct: 2, explain: "Ang pi ay irrational number dahil hindi ito maisusulat bilang eksaktong fraction at walang paulit-ulit na pattern ang decimals nito." },
      { text: "Ano ang sagot sa 7 mod 3 (natitira kapag hinati)?", choices: ["1", "2", "3", "0"], correct: 1, explain: "Kapag hinati ang 7 sa 3, ang natitira o remainder ay 1." },
      { text: "Ano ang sagot sa 0.15 x 0.15?", choices: ["0.0225", "0.225", "2.25", "0.225%"], correct: 1, explain: "Kapag pinarami ang 0.15 sa sarili nito, ang resulta ay 0.0225." },
      { text: "Ano ang sagot sa 2/5 na ginawang percent?", choices: ["20%", "40%", "25%", "45%"], correct: 2, explain: "Ang 2/5 kapag ginawang percent ay 40% dahil 2÷5=0.4." },
      { text: "Ano ang sagot sa cube root ng 27?", choices: ["2", "3", "4", "9"], correct: 2, explain: "Ang cube root ng 27 ay 3 dahil 3x3x3=27." },
      { text: "Ano ang sagot sa 6 x 10⁻² sa decimal form?", choices: ["0.06", "0.6", "60", "0.006"], correct: 1, explain: "Ang negative exponent ay nangangahulugang ilipat ang decimal point pakaliwa, kaya 6x10⁻²=0.06." }
    ]
  },
  Algebra: {
    low: [
      { text: "Ano ang sagot kung x + 4 = 9?", choices: ["x=13", "x=5", "x=4", "x=9"], correct: 2, explain: "Ibawas ang 4 sa magkabilang panig para makuha ang x=5." },
      { text: "Ano ang tawag sa letra na kumakatawan sa hindi alam na numero?", choices: ["Constant", "Variable", "Coefficient", "Exponent"], correct: 2, explain: "Ang variable ay letra na kumakatawan sa isang hindi pa alam na numero." },
      { text: "Ano ang coefficient sa 5x?", choices: ["x", "5", "5x", "1"], correct: 2, explain: "Ang coefficient ay ang numerong nasa harap ng variable, kaya sa 5x, ito ay 5." },
      { text: "Ano ang sagot kung i-simplify ang 3x + 2x?", choices: ["5x", "6x", "x", "5x²"], correct: 1, explain: "Dahil parehong may x, idinadagdag lang ang coefficients: 3x+2x=5x." },
      { text: "Ano ang sagot kung x = 3 sa expression na 2x + 1?", choices: ["5", "6", "7", "8"], correct: 3, explain: "Palitan ang x ng 3: 2(3)+1=6+1=7." },
      { text: "Ano ang sagot sa 4y - y?", choices: ["3", "3y", "4y", "y"], correct: 2, explain: "Ang y ay katumbas ng 1y, kaya 4y-1y=3y." },
      { text: "Anong operasyon ang ginagawa muna sa PEMDAS pagkatapos ng parenthesis?", choices: ["Addition", "Subtraction", "Exponent", "Multiplication"], correct: 3, explain: "Sunod sa parenthesis sa PEMDAS ang exponent bago ang multiplication o division." },
      { text: "Ano ang sagot sa 2(x+3) kapag na-distribute?", choices: ["2x+3", "2x+6", "x+6", "2x+5"], correct: 2, explain: "I-distribute ang 2 sa bawat termino sa loob ng parenthesis: 2(x)+2(3)=2x+6." },
      { text: "Ano ang tawag sa numerong hindi nagbabago ang value, hal. 7 sa 7+x?", choices: ["Variable", "Constant", "Exponent", "Term"], correct: 2, explain: "Ang constant ay numerong hindi nagbabago ang value tulad ng 7 sa expression na 7+x." },
      { text: "Ano ang sagot kung 3x = 12?", choices: ["x=3", "x=4", "x=6", "x=9"], correct: 2, explain: "Hatiin ang 12 sa 3 para makuha ang x=4." },
      { text: "Ano ang sagot sa x² kapag x=4?", choices: ["8", "16", "12", "4"], correct: 2, explain: "Palitan ang x ng 4: 4²=4x4=16." },
      { text: "Ano ang sagot sa -2x kapag x = -5?", choices: ["-10", "10", "-3", "3"], correct: 2, explain: "Palitan ang x ng -5: -2(-5)=10 dahil negatibo x negatibo ay positibo." },
      { text: "Ilang termino mayroon ang expression na 3x + 2y - 5?", choices: ["1", "2", "3", "4"], correct: 3, explain: "May tatlong hiwalay na termino ang expression: 3x, 2y, at -5." },
      { text: "Ano ang sagot kung i-solve ang x/2 = 6?", choices: ["x=3", "x=8", "x=12", "x=6"], correct: 3, explain: "Paramihin ang 6 sa 2 para makuha ang x=12." },
      { text: "Ano ang tawag sa equation na may equal sign at isang variable sa unang degree?", choices: ["Quadratic equation", "Linear equation", "Exponential equation", "Polynomial"], correct: 2, explain: "Ang linear equation ay may variable na unang degree lamang, walang exponent." }
    ],
    mid: [
      { text: "Ano ang sagot kung i-solve ang 2x + 3 = x + 9?", choices: ["x=3", "x=6", "x=9", "x=12"], correct: 2, explain: "Ibawas ang x sa magkabilang panig (x+3=9) tapos ibawas ang 3 para makuha ang x=6." },
      { text: "Ano ang slope ng linyang dumadaan sa (0,0) at (2,4)?", choices: ["1", "2", "4", "1/2"], correct: 2, explain: "Ang slope ay pagbabago sa y hati sa pagbabago sa x: (4-0)/(2-0)=2." },
      { text: "Ano ang y-intercept ng equation na y = 3x + 5?", choices: ["3", "5", "-5", "0"], correct: 2, explain: "Ang y-intercept ay ang constant term kapag x=0, kaya ito ay 5." },
      { text: "Ano ang sagot kung i-factor ang x² - 9?", choices: ["(x-3)(x+3)", "(x-9)(x+1)", "(x-3)²", "(x+9)(x-1)"], correct: 1, explain: "Ang x²-9 ay difference of squares na nagiging (x-3)(x+3) kapag na-factor." },
      { text: "Ano ang sagot sa (x+2)(x+3) kapag na-expand?", choices: ["x²+5x+6", "x²+6x+5", "x²+5x+5", "x²+6"], correct: 1, explain: "Gamit ang FOIL, ang (x+2)(x+3) ay nagiging x²+3x+2x+6=x²+5x+6." },
      { text: "Ano ang tawag sa pinakamataas na exponent sa isang polynomial?", choices: ["Coefficient", "Degree", "Term", "Constant"], correct: 2, explain: "Ang degree ang tawag sa pinakamataas na exponent ng isang polynomial." },
      { text: "Ano ang sagot kung i-solve ang system: x+y=10, x-y=2?", choices: ["x=6,y=4", "x=4,y=6", "x=5,y=5", "x=8,y=2"], correct: 1, explain: "Idagdag ang dalawang equation para makuha ang 2x=12, kaya x=6 at y=4." },
      { text: "Ano ang standard form ng linear equation?", choices: ["y=mx+b", "Ax+By=C", "y=a(x-h)²+k", "y=ax²+bx+c"], correct: 2, explain: "Ang Ax+By=C ang tinatawag na standard form ng linear equation." },
      { text: "Ano ang sagot kung i-simplify ang (3x²)(2x³)?", choices: ["6x⁵", "6x⁶", "5x⁵", "6x"], correct: 1, explain: "Paramihin ang coefficients (3x2=6) at idagdag ang exponents (2+3=5), kaya 6x⁵." },
      { text: "Ano ang sagot kung x²=16?", choices: ["x=4 lang", "x=4 o x=-4", "x=8", "x=16"], correct: 2, explain: "Parehong positibo at negatibong 4 kapag naka-square ay nagbibigay ng 16." },
      { text: "Ano ang tawag sa dalawang termino na polynomial?", choices: ["Monomial", "Binomial", "Trinomial", "Polynomial"], correct: 2, explain: "Ang binomial ay polynomial na may eksaktong dalawang termino." },
      { text: "Ano ang sagot sa 3x - 7 = 2x + 1?", choices: ["x=6", "x=8", "x=-6", "x=-8"], correct: 2, explain: "Ibawas ang 2x sa magkabilang panig (x-7=1) tapos idagdag ang 7 para makuha ang x=8." },
      { text: "Ano ang slope-intercept form ng linear equation?", choices: ["Ax+By=C", "y=mx+b", "y=a(x-h)²+k", "y-y1=m(x-x1)"], correct: 2, explain: "Ang y=mx+b ang tawag sa slope-intercept form kung saan m ang slope at b ang y-intercept." },
      { text: "Ano ang sagot kung i-evaluate ang f(x)=2x+1 sa x=3?", choices: ["5", "6", "7", "8"], correct: 3, explain: "Palitan ang x ng 3: 2(3)+1=6+1=7." },
      { text: "Ano ang tawag sa equation na may pinakamataas na exponent na 2?", choices: ["Linear equation", "Quadratic equation", "Cubic equation", "Exponential equation"], correct: 2, explain: "Ang quadratic equation ay may pinakamataas na exponent na 2 sa variable nito." }
    ],
    high: [
      { text: "Ano ang quadratic formula?", choices: ["x = -b±√(b²-4ac) / 2a", "x = -b±√(b²+4ac) / 2a", "x = b±√(b²-4ac) / 2a", "x = -b±√(b²-4ac) / a"], correct: 1, explain: "Ito ang standard na quadratic formula na ginagamit para hanapin ang mga ugat ng anumang quadratic equation." },
      { text: "Ano ang discriminant ng quadratic equation?", choices: ["b²-4ac", "b²+4ac", "4ac-b²", "a²-4bc"], correct: 1, explain: "Ang b²-4ac ang discriminant na nagsasabi kung ilan at anong uri ng roots mayroon ang equation." },
      { text: "Kung ang discriminant ay negative, ilan ang real roots ng quadratic equation?", choices: ["2", "1", "0", "3"], correct: 3, explain: "Kapag negative ang discriminant, walang real roots ang equation — imaginary lang ang mga ito." },
      { text: "Ano ang sagot kung i-solve ang x² - 5x + 6 = 0?", choices: ["x=2,3", "x=1,6", "x=-2,-3", "x=2,-3"], correct: 1, explain: "Ang x²-5x+6 ay na-factor bilang (x-2)(x-3), kaya x=2 o x=3." },
      { text: "Ano ang vertex form ng quadratic function?", choices: ["y=mx+b", "y=a(x-h)²+k", "Ax+By=C", "y=ax+b"], correct: 2, explain: "Ang y=a(x-h)²+k ang vertex form kung saan (h,k) ang vertex ng parabola." },
      { text: "Ano ang tawag sa function na may exponent na variable, hal. 2ˣ?", choices: ["Linear function", "Quadratic function", "Exponential function", "Logarithmic function"], correct: 3, explain: "Ang exponential function ay may variable sa exponent tulad ng 2ˣ." },
      { text: "Ano ang inverse function ng f(x) = x + 5?", choices: ["f⁻¹(x) = x - 5", "f⁻¹(x) = x + 5", "f⁻¹(x) = -x - 5", "f⁻¹(x) = 5x"], correct: 1, explain: "Para mabaligtad ang f(x)=x+5, ibawas ang 5 sa halip na idagdag, kaya f⁻¹(x)=x-5." },
      { text: "Ano ang domain ng function na f(x) = 1/x?", choices: ["Lahat ng numero", "Lahat maliban sa 0", "Positive numbers lang", "Negative numbers lang"], correct: 2, explain: "Hindi maaaring maging 0 ang denominator, kaya ang domain ay lahat ng numero maliban sa 0." },
      { text: "Ano ang sagot sa pag-factor ng x² + 6x + 9?", choices: ["(x+3)²", "(x+9)(x+1)", "(x-3)²", "(x+3)(x-3)"], correct: 1, explain: "Ang x²+6x+9 ay perfect square trinomial na katumbas ng (x+3)²." },
      { text: "Anong uri ng sequence ang may constant na ratio sa magkasunod na termino?", choices: ["Arithmetic sequence", "Geometric sequence", "Fibonacci sequence", "Random sequence"], correct: 2, explain: "Sa geometric sequence, may pare-parehong ratio sa pagitan ng magkasunod na termino." },
      { text: "Anong uri ng sequence ang may constant na difference sa magkasunod na termino?", choices: ["Geometric sequence", "Arithmetic sequence", "Harmonic sequence", "Random sequence"], correct: 2, explain: "Sa arithmetic sequence, may pare-parehong difference sa pagitan ng magkasunod na termino." },
      { text: "Ano ang sagot sa sum ng unang 5 terms ng arithmetic sequence 2,4,6,8,10?", choices: ["20", "25", "30", "35"], correct: 3, explain: "Kapag idinagdag ang 2+4+6+8+10, ang kabuuan ay 30." },
      { text: "Ano ang tawag sa graph ng quadratic function?", choices: ["Line", "Parabola", "Circle", "Hyperbola"], correct: 2, explain: "Ang graph ng quadratic function ay laging hugis parabola." },
      { text: "Ano ang sagot kung i-solve ang |x - 3| = 5?", choices: ["x=8 lang", "x=8 o x=-2", "x=2 o x=-8", "x=-8 lang"], correct: 2, explain: "Dahil absolute value, maaaring x-3=5 o x-3=-5, kaya x=8 o x=-2." },
      { text: "Ano ang tawag sa sistema ng equations na walang solusyon?", choices: ["Consistent", "Inconsistent", "Dependent", "Independent"], correct: 2, explain: "Tinatawag na inconsistent ang sistema ng equations na walang kahit anong solusyon." }
    ]
  },
  Geometry: {
    low: [
      { text: "Ilang degrees ang isang right angle?", choices: ["45", "90", "180", "360"], correct: 2, explain: "Ang right angle ay eksaktong 90 degrees." },
      { text: "Ilang degrees ang kabuuan ng anggulo ng isang triangle?", choices: ["90", "180", "270", "360"], correct: 2, explain: "Ang kabuuan ng lahat ng anggulo sa loob ng triangle ay palaging 180 degrees." },
      { text: "Ano ang tawag sa polygon na may 3 sides?", choices: ["Square", "Triangle", "Pentagon", "Hexagon"], correct: 2, explain: "Ang triangle ay polygon na may eksaktong tatlong sides." },
      { text: "Ano ang tawag sa polygon na may 4 na magkaparehong sides at anggulo?", choices: ["Rectangle", "Square", "Rhombus", "Trapezoid"], correct: 2, explain: "Ang square ay may apat na magkaparehong sides at apat na 90-degree na anggulo." },
      { text: "Ano ang perimeter ng square na may side na 5cm?", choices: ["10cm", "15cm", "20cm", "25cm"], correct: 3, explain: "Paramihin ang 5cm sa apat na sides: 5x4=20cm." },
      { text: "Ano ang area ng rectangle na 4cm x 6cm?", choices: ["10cm²", "20cm²", "24cm²", "28cm²"], correct: 3, explain: "Paramihin ang base at height: 4x6=24cm²." },
      { text: "Ano ang tawag sa linya na hindi na magsasalubong kahit anong haba?", choices: ["Intersecting lines", "Parallel lines", "Perpendicular lines", "Diagonal lines"], correct: 2, explain: "Ang parallel lines ay dalawang linyang pantay ang layo at hindi kailanman nagsasalubong." },
      { text: "Ano ang tawag sa dalawang linyang nagtatagpo sa 90 degrees?", choices: ["Parallel lines", "Perpendicular lines", "Curved lines", "Diagonal lines"], correct: 2, explain: "Ang perpendicular lines ay nagtatagpo nang eksaktong 90 degrees." },
      { text: "Ano ang tawag sa anggulong mas mababa sa 90 degrees?", choices: ["Obtuse angle", "Acute angle", "Right angle", "Straight angle"], correct: 2, explain: "Ang acute angle ay anumang anggulong mas mababa sa 90 degrees." },
      { text: "Ano ang tawag sa anggulong mas malaki sa 90 pero mas mababa sa 180 degrees?", choices: ["Acute angle", "Right angle", "Obtuse angle", "Reflex angle"], correct: 3, explain: "Ang obtuse angle ay nasa pagitan ng 90 at 180 degrees." },
      { text: "Ano ang tawag sa distansya mula sa gitnang punto ng isang circle papunta sa gilid nito?", choices: ["Diameter", "Radius", "Circumference", "Chord"], correct: 2, explain: "Ang radius ay ang distansya mula sa gitna ng circle papunta sa gilid nito." },
      { text: "Ano ang tawag sa distansya sa palibot ng circle?", choices: ["Radius", "Diameter", "Circumference", "Area"], correct: 3, explain: "Ang circumference ang tawag sa distansya sa buong palibot ng isang circle." },
      { text: "Ilan ang sides ng isang hexagon?", choices: ["5", "6", "7", "8"], correct: 2, explain: "Ang hexagon ay polygon na may anim na sides." },
      { text: "Ano ang tawag sa 3D na hugis na may 6 na parisukat na mukha?", choices: ["Sphere", "Cube", "Cylinder", "Cone"], correct: 2, explain: "Ang cube ay may anim na magkaparehong parisukat na mukha." },
      { text: "Ano ang tawag sa dalawang magkatapat na sides ng isang parallelogram?", choices: ["Perpendicular", "Parallel", "Diagonal", "Adjacent"], correct: 2, explain: "Sa parallelogram, ang magkatapat na sides ay laging parallel sa isa't isa." }
    ],
    mid: [
      { text: "Ano ang Pythagorean theorem formula?", choices: ["a+b=c", "a²+b²=c²", "a²-b²=c²", "a²×b²=c²"], correct: 2, explain: "Sinasabi ng Pythagorean theorem na ang sum ng squares ng dalawang legs ay katumbas ng square ng hypotenuse." },
      { text: "Kung ang legs ng right triangle ay 3 at 4, ano ang hypotenuse?", choices: ["5", "6", "7", "8"], correct: 1, explain: "Gamit ang Pythagorean theorem, √(3²+4²)=√25=5." },
      { text: "Ano ang area ng circle kung ang radius ay 7 (gamit ang π≈22/7)?", choices: ["154", "144", "164", "174"], correct: 1, explain: "Ang area ay πr², kaya (22/7)x7x7=154." },
      { text: "Ano ang formula ng area ng triangle?", choices: ["base x height", "1/2 x base x height", "base + height", "2 x base x height"], correct: 2, explain: "Ang area ng triangle ay kalahati ng produkto ng base at height." },
      { text: "Ano ang tawag sa mga anggulong ang kabuuan ay 180 degrees?", choices: ["Complementary angles", "Supplementary angles", "Vertical angles", "Adjacent angles"], correct: 2, explain: "Ang supplementary angles ay dalawang anggulong ang kabuuan ay 180 degrees." },
      { text: "Ano ang tawag sa mga anggulong ang kabuuan ay 90 degrees?", choices: ["Complementary angles", "Supplementary angles", "Vertical angles", "Corresponding angles"], correct: 1, explain: "Ang complementary angles ay dalawang anggulong ang kabuuan ay 90 degrees." },
      { text: "Ano ang sum ng interior angles ng isang quadrilateral?", choices: ["180", "270", "360", "450"], correct: 3, explain: "Ang kabuuan ng interior angles ng anumang quadrilateral ay laging 360 degrees." },
      { text: "Ano ang tawag sa hugis na may parehong shape at size?", choices: ["Similar figures", "Congruent figures", "Symmetrical figures", "Regular figures"], correct: 2, explain: "Ang congruent figures ay may eksaktong parehong shape at size." },
      { text: "Ano ang tawag sa hugis na may parehong shape pero magkaibang size?", choices: ["Congruent figures", "Similar figures", "Identical figures", "Regular figures"], correct: 2, explain: "Ang similar figures ay may parehong shape ngunit magkaiba ang size." },
      { text: "Ano ang volume ng cube na may side na 3cm?", choices: ["9cm³", "18cm³", "27cm³", "36cm³"], correct: 3, explain: "Ang volume ng cube ay side³, kaya 3x3x3=27cm³." },
      { text: "Ano ang formula sa circumference ng circle?", choices: ["πr²", "2πr", "πd²", "2πd"], correct: 2, explain: "Ang circumference ng circle ay katumbas ng 2πr." },
      { text: "Ano ang tawag sa linyang dumadaan sa gitna ng circle mula gilid papunta sa gilid?", choices: ["Radius", "Chord", "Diameter", "Tangent"], correct: 3, explain: "Ang diameter ay linyang dumadaan sa gitna ng circle mula sa isang gilid papunta sa kabilang gilid." },
      { text: "Ano ang formula ng area ng parallelogram?", choices: ["base x height", "1/2 base x height", "base + height", "2(base+height)"], correct: 1, explain: "Ang area ng parallelogram ay katumbas ng base na pinarami sa height." },
      { text: "Ilan ang diagonals ng isang pentagon?", choices: ["3", "4", "5", "6"], correct: 3, explain: "Ang isang regular pentagon ay may limang diagonals." },
      { text: "Ano ang tawag sa 3D shape na may isang circular base at isang punto sa taas?", choices: ["Cylinder", "Cone", "Sphere", "Prism"], correct: 2, explain: "Ang cone ay may isang circular base at nagtatapos sa isang punto sa taas." }
    ],
    high: [
      { text: "Ano ang formula ng distance sa pagitan ng dalawang points (x1,y1) at (x2,y2)?", choices: ["√((x2-x1)+(y2-y1))", "√((x2-x1)²+(y2-y1)²)", "(x2-x1)²+(y2-y1)²", "√(x2+y2)"], correct: 2, explain: "Ang distance formula ay hango sa Pythagorean theorem gamit ang pagkakaiba ng x at y coordinates." },
      { text: "Ano ang midpoint formula sa pagitan ng dalawang points?", choices: ["((x1+x2)/2, (y1+y2)/2)", "(x1+x2, y1+y2)", "((x1-x2)/2, (y1-y2)/2)", "(x1x2, y1y2)"], correct: 1, explain: "Ang midpoint ay ang average ng x-coordinates at average ng y-coordinates ng dalawang points." },
      { text: "Ano ang sum of interior angles ng isang polygon na may n sides?", choices: ["(n-2) x 180", "n x 180", "(n+2) x 180", "n x 90"], correct: 1, explain: "Ang formula na (n-2) x 180 ang ginagamit para makuha ang sum of interior angles ng anumang polygon." },
      { text: "Ano ang formula ng volume ng cylinder?", choices: ["πr²h", "2πrh", "πr²+h", "πrh²"], correct: 1, explain: "Ang volume ng cylinder ay katumbas ng area ng circular base (πr²) na pinarami sa height." },
      { text: "Ano ang formula ng surface area ng sphere?", choices: ["4πr²", "πr²", "2πr²", "4πr³/3"], correct: 1, explain: "Ang surface area ng sphere ay katumbas ng 4πr²." },
      { text: "Ano ang formula ng volume ng sphere?", choices: ["4πr²/3", "4πr³/3", "πr³", "2πr³"], correct: 2, explain: "Ang volume ng sphere ay katumbas ng 4πr³/3." },
      { text: "Anong theorem ang ginagamit para malaman kung congruent ang dalawang triangle gamit ang side-angle-side?", choices: ["SSS", "SAS", "AAS", "ASA"], correct: 2, explain: "Ang SAS (Side-Angle-Side) theorem ay ginagamit kapag dalawang sides at ang anggulo sa pagitan nila ay pareho sa dalawang triangle." },
      { text: "Ano ang tawag sa ratio ng magkatugmang sides sa similar figures?", choices: ["Scale factor", "Congruence ratio", "Perimeter ratio", "Area ratio"], correct: 1, explain: "Ang scale factor ang ratio ng magkatugmang sides ng dalawang similar figures." },
      { text: "Sa SOH-CAH-TOA, ano ang kinakatawan ng SOH?", choices: ["Cos = adjacent/hypotenuse", "Sin = opposite/hypotenuse", "Tan = opposite/adjacent", "Sin = adjacent/hypotenuse"], correct: 2, explain: "SOH ay nangangahulugang Sin ay katumbas ng opposite hati sa hypotenuse." },
      { text: "Sa SOH-CAH-TOA, ano ang kinakatawan ng CAH?", choices: ["Cos = adjacent/hypotenuse", "Sin = opposite/hypotenuse", "Tan = opposite/adjacent", "Cos = opposite/hypotenuse"], correct: 1, explain: "CAH ay nangangahulugang Cos ay katumbas ng adjacent hati sa hypotenuse." },
      { text: "Sa SOH-CAH-TOA, ano ang kinakatawan ng TOA?", choices: ["Tan = adjacent/opposite", "Tan = opposite/adjacent", "Tan = opposite/hypotenuse", "Tan = hypotenuse/opposite"], correct: 2, explain: "TOA ay nangangahulugang Tan ay katumbas ng opposite hati sa adjacent." },
      { text: "Ano ang tawag sa linyang tumatama sa circle sa isang punto lamang?", choices: ["Chord", "Secant", "Tangent", "Radius"], correct: 3, explain: "Ang tangent ay linyang tumatama sa circle sa isang punto lamang." },
      { text: "Ano ang tawag sa anggulong nabuo sa gitna ng circle?", choices: ["Inscribed angle", "Central angle", "Exterior angle", "Reflex angle"], correct: 2, explain: "Ang central angle ay anggulong ang vertex ay nasa gitna mismo ng circle." },
      { text: "Ano ang formula ng area ng trapezoid?", choices: ["1/2(b1+b2)h", "(b1+b2)h", "1/2(b1xb2)h", "b1+b2+h"], correct: 1, explain: "Ang area ng trapezoid ay kalahati ng kabuuan ng dalawang bases na pinarami sa height." },
      { text: "Ano ang tawag sa teorama na nagsasabing ang sum ng squares ng legs ay katumbas ng square ng hypotenuse sa right triangle?", choices: ["Law of Cosines", "Pythagorean Theorem", "Law of Sines", "Distance Formula"], correct: 2, explain: "Ito mismo ang depinisyon ng Pythagorean Theorem." }
    ]
  }
};
